### ISSUE TITLE
can not scroll down the navigation part in the documentation page

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/CloudSlang.github.io#58]
using Chrome

![image](https://cloud.githubusercontent.com/assets/6059211/6886561/2b0d0f98-d64a-11e4-9018-32ba8580a45c.png)

**Comment by orius123** [comment]
fixed @meirwah
please verify

**Comment by meirwah** [comment]
still see issue (on main website,) did you fix it on branch?
screen resolution  is 1920x1080

**Comment by orius123** [comment]
Fixed on master.. Is the bar green or white for you? Try to clear cache..

**Comment by meirwah** [comment]
![image](https://cloud.githubusercontent.com/assets/6059211/6890731/6e148bbc-d6b9-11e4-83f0-13727dcd145c.png)

**Comment by SamMarkowitz** [comment]
I can scroll, but there is an ugly looking scroll bar that doesn't do anything that shows up at the top of the page:
![image](https://cloud.githubusercontent.com/assets/9436355/6890747/d815297c-d6b9-11e4-9a1b-2cbbac12e1c5.png)

**Comment by orius123** [comment]
ok.
as weird as it sound I have a different behavior which is also not fine..
will look into it later today.
can you both try in anonymous mode please?
http://cloudslang.io

**Comment by meirwah** [comment]
same in anonymous mode ...

**Comment by SamMarkowitz** [comment]
The green bleeds past the scrollbar (which now works fine) when page loads up. After scrolling it disappears.

![image](https://cloud.githubusercontent.com/assets/9436355/6891082/2143699c-d6bf-11e4-8ff8-b44bd9528f9c.png)

**Comment by orius123** [comment]
ok.
tried to fix it can you try again after cleaning cache or in anonymous mode?
please

**Comment by meirwah** [comment]
:+1:
